export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';

export const SET_RESET_MESSAGES = 'SET_RESET_MESSAGES';

export const MESSAGE_STORE = 'MESSAGE_STORE';
export const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE';
export const GET_MORE_MESSAGES = 'GET_MORE_MESSAGES';
