export const GET_FEEDBACK_LIST_REQUEST = 'GET_FEEDBACK_LIST_REQUEST';
export const GET_FEEDBACK_LIST_SUCCESS = 'GET_FEEDBACK_LIST_SUCCESS';
export const GET_FEEDBACK_LIST_ERROR = 'GET_FEEDBACK_LIST_ERROR';
