export const GET_FEEDBACK_LIST_REQUEST = 'GET_FEEDBACK_LIST_REQUEST';
export const GET_FEEDBACK_LIST_SUCCESS = 'GET_FEEDBACK_LIST_SUCCESS';
export const GET_FEEDBACK_LIST_ERROR = 'GET_FEEDBACK_LIST_ERROR';

export const LEAVE_FEEDBACK_REQUEST = 'LEAVE_FEEDBACK_REQUEST';
export const LEAVE_FEEDBACK_SUCCESS = 'LEAVE_FEEDBACK_SUCCESS';
export const LEAVE_FEEDBACK_ERROR = 'LEAVE_FEEDBACK_ERROR';
