export const GET_VOUCHES_REQUEST = 'GET_VOUCHES_REQUEST';
export const GET_VOUCHES_SUCCESS = 'GET_VOUCHES_SUCCESS';
export const GET_VOUCHES_ERROR = 'GET_VOUCHES_ERROR';

export const CREATE_VOUCH_REQUEST = 'CREATE_VOUCH_REQUEST';
export const CREATE_VOUCH_SUCCESS = 'CREATE_VOUCH_SUCCESS';
export const CREATE_VOUCH_ERROR = 'CREATE_VOUCH_ERROR';

export const DELETE_VOUCH_REQUEST = 'DELETE_VOUCH_REQUEST';
export const DELETE_VOUCH_SUCCESS = 'DELETE_VOUCH_SUCCESS';
export const DELETE_VOUCH_ERROR = 'DELETE_VOUCH_ERROR';

export const ACCEPT_VOUCH_REQUEST = 'ACCEPT_VOUCH_REQUEST';
export const ACCEPT_VOUCH_SUCCESS = 'ACCEPT_VOUCH_SUCCESS';
export const ACCEPT_VOUCH_ERROR = 'ACCEPT_VOUCH_ERROR';

export const REJECT_VOUCH_REQUEST = 'REJECT_VOUCH_REQUEST';
export const REJECT_VOUCH_SUCCESS = 'REJECT_VOUCH_SUCCESS';
export const REJECT_VOUCH_ERROR = 'REJECT_VOUCH_ERROR';
