export const GET_PROPOSALS_REQUEST = 'GET_PROPOSALS_REQUEST';
export const GET_PROPOSALS_SUCCESS = 'GET_PROPOSALS_SUCCESS';
export const GET_PROPOSALS_ERROR = 'GET_PROPOSALS_ERROR';

export const CREATE_PROPOSAL_REQUEST = 'CREATE_PROPOSAL_REQUEST';
export const CREATE_PROPOSAL_SUCCESS = 'CREATE_PROPOSAL_SUCCESS';
export const CREATE_PROPOSAL_ERROR = 'CREATE_PROPOSAL_ERROR';

export const UPDATE_PROPOSAL_REQUEST = 'UPDATE_PROPOSAL_REQUEST';
export const UPDATE_PROPOSAL_SUCCESS = 'UPDATE_PROPOSAL_SUCCESS';
export const UPDATE_PROPOSAL_ERROR = 'UPDATE_PROPOSAL_ERROR';

export const DELETE_PROPOSAL_REQUEST = 'DELETE_PROPOSAL_REQUEST';
export const DELETE_PROPOSAL_SUCCESS = 'DELETE_PROPOSAL_SUCCESS';
export const DELETE_PROPOSAL_ERROR = 'DELETE_PROPOSAL_ERROR';

export const ACCEPT_PROPOSAL_REQUEST = 'ACCEPT_PROPOSAL_REQUEST';
export const ACCEPT_PROPOSAL_SUCCESS = 'ACCEPT_PROPOSAL_SUCCESS';
export const ACCEPT_PROPOSAL_ERROR = 'ACCEPT_PROPOSAL_ERROR';

export const REJECT_PROPOSAL_REQUEST = 'REJECT_PROPOSAL_REQUEST';
export const REJECT_PROPOSAL_SUCCESS = 'REJECT_PROPOSAL_SUCCESS';
export const REJECT_PROPOSAL_ERROR = 'REJECT_PROPOSAL_ERROR';
