// accecpt application as member
export const ACCEPT_APPLICATION_REQUEST = 'ACCEPT_APPLICATION_REQUEST';
export const ACCEPT_APPLICATION_SUCCESS = 'ACCEPT_APPLICATION_SUCCESS';
export const ACCEPT_APPLICATION_ERROR = 'ACCEPT_MEMBER_ERROR';

// reject application
export const REJECT_APPLICATION_REQUEST = 'REJECT_APPLICATION_REQUEST';
export const REJECT_APPLICATION_SUCCESS = 'REJECT_APPLICATION_SUCCESS';
export const REJECT_APPLICATION_ERROR = 'REJECT_APPLICATION_ERROR';

// make admin
export const MAKE_ADMIN_REQUEST = 'MAKE_ADMIN_REQUEST';
export const MAKE_ADMIN_SUCCESS = 'MAKE_ADMIN_SUCCESS';
export const MAKE_ADMIN_ERROR = 'MAKE_ADMIN_ERROR';

// ban user
export const BAN_USER_REQUEST = 'BAN_USER_REQUEST';
export const BAN_USER_SUCCESS = 'BAN_USER_SUCCESS';
export const BAN_USER_ERROR = 'BAN_USER_ERROR';

// unban user
export const UNBAN_USER_REQUEST = 'UNBAN_USER_REQUEST';
export const UNBAN_USER_SUCCESS = 'UNBAN_USER_SUCCESS';
export const UNBAN_USER_ERROR = 'UNBAN_USER_ERROR';
