export const GET_MY_PROPOSALS_REQUEST = 'GET_MY_PROPOSALS_REQUEST';
export const GET_MY_PROPOSALS_SUCCESS = 'GET_MY_PROPOSALS_SUCCESS';
export const GET_MY_PROPOSALS_ERROR = 'GET_MY_PROPOSALS_ERROR';
