export const GET_OFFERS_REQUEST = 'GET_OFFERS_REQUEST';
export const GET_OFFERS_SUCCESS = 'GET_OFFERS_SUCCESS';
export const GET_OFFERS_ERROR = 'GET_OFFERS_ERROR';

export const CREATE_OFFER_REQUEST = 'CREATE_OFFER_REQUEST';
export const CREATE_OFFER_SUCCESS = 'CREATE_OFFER_SUCCESS';
export const CREATE_OFFER_ERROR = 'CREATE_OFFER_ERROR';

export const READ_OFFER_REQUEST = 'READ_OFFER_REQUEST';
export const READ_OFFER_SUCCESS = 'READ_OFFER_SUCCESS';
export const READ_OFFER_ERROR = 'READ_OFFER_ERROR';

export const UPDATE_OFFER_REQUEST = 'UPDATE_OFFER_REQUEST';
export const UPDATE_OFFER_SUCCESS = 'UPDATE_OFFER_SUCCESS';
export const UPDATE_OFFER_ERROR = 'UPDATE_OFFER_ERROR';

export const DELETE_OFFER_REQUEST = 'DELETE_OFFER_REQUEST';
export const DELETE_OFFER_SUCCESS = 'DELETE_OFFER_SUCCESS';
export const DELETE_OFFER_ERROR = 'DELETE_OFFER_ERROR';

export const END_OFFER_REQUEST = 'END_OFFER_REQUEST';
export const END_OFFER_SUCCESS = 'END_OFFER_SUCCESS';
export const END_OFFER_ERROR = 'END_OFFER_ERROR';
