// get profile constants
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';

// group join request constants
export const JOIN_GROUP_REQUEST = 'JOIN_GROUP_REQUEST';
export const JOIN_GROUP_SUCCESS = 'JOIN_GROUP_SUCCESS';
export const JOIN_GROUP_ERROR = 'JOIN_GROUP_ERROR';

// my offers
export const GET_MY_OFFERS_REQUEST = 'GET_MY_OFFERS_REQUEST';
export const GET_MY_OFFERS_SUCCESS = 'GET_MY_OFFERS_SUCCESS';
export const GET_MY_OFFERS_ERROR = 'GET_MY_OFFERS_ERROR';

export const DELETE_MY_OFFER = 'DELETE_MY_OFFER';
