export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';

export const SIGNOUT = 'SIGNOUT';

// email confirm
export const SEND_CONFIRM_REQUEST = 'SEND_CONFIRM_REQUEST';
export const SEND_CONFIRM_SUCCESS = 'SEND_CONFIRM_SUCCESS';
export const SEND_CONFIRM_ERROR = 'SEND_CONFIRM_ERROR';

// email confirm
export const VERIFY_EMAIL_REQUEST = 'VERIFY_EMAIL_REQUEST';
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_ERROR = 'VERIFY_EMAIL_ERROR';

// forgot password
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';
export const RESET_FORGOT_PASSWORD_STEP = 'RESET_FORGOT_PASSWORD_STEP';

// confirm password
export const CONFIRM_PASSWORD_REQUEST = 'CONFIRM_PASSWORD_REQUEST';
export const CONFIRM_PASSWORD_ERROR = 'CONFIRM_PASSWORD_ERROR';

// generate two factor auth
export const GENERATE_TWO_FA_REQUEST = 'GENERATE_TWO_FA_REQUEST';
export const GENERATE_TWO_FA_SUCCESS = 'GENERATE_TWO_FA_SUCCESS';
export const GENERATE_TWO_FA_ERROR = 'GENERATE_TWO_FA_ERROR';

// confirm two factor auth
export const CONFIRM_TWO_FA_REQUEST = 'CONFIRM_TWO_FA_REQUEST';
export const CONFIRM_TWO_FA_SUCCESS = 'CONFIRM_TWO_FA_SUCCESS';
export const CONFIRM_TWO_FA_ERROR = 'CONFIRM_TWO_FA_ERROR';

export const DISABLE_TWO_FA_REQUEST = 'DISABLE_TWO_FA_REQUEST';
