export const GET_GROUP_MEMBERS_REQUEST = 'GET_GROUP_MEMBERS_REQUEST';
export const GET_GROUP_MEMBERS_SUCCESS = 'GET_GROUP_MEMBERS_SUCCESS';
export const GET_GROUP_MEMBERS_ERROR = 'GET_GROUP_MEMBERS_ERROR';

export const GET_PERMISSION_GROUPS_REQUEST = 'GET_PERMISSION_GROUPS_REQUEST';
export const GET_PERMISSION_GROUPS_SUCCESS = 'GET_PERMISSION_GROUPS_SUCCESS';
export const GET_PERMISSION_GROUPS_ERROR = 'GET_PERMISSION_GROUPS_ERROR';

export const READ_USER_REQUEST = 'READ_USER_REQUEST';
export const READ_USER_SUCCESS = 'READ_USER_SUCCESS';
export const READ_USER_ERROR = 'READ_USER_ERROR';

export const SELECT_ACTIVE_GROUP = 'SELECT_ACTIVE_GROUP';
export const SELECT_GROUP_MEMBER = 'SELECT_GROUP_MEMBER';
