export const GET_GROUP_MEMBERS_REQUEST = 'GET_GROUP_MEMBERS_REQUEST';
export const GET_GROUP_MEMBERS_SUCCESS = 'GET_GROUP_MEMBERS_SUCCESS';
export const GET_GROUP_MEMBERS_ERROR = 'GET_GROUP_MEMBERS_ERROR';

export const GET_PERMISSION_GROUPS_REQUEST = 'GET_PERMISSION_GROUPS_REQUEST';
export const GET_PERMISSION_GROUPS_SUCCESS = 'GET_PERMISSION_GROUPS_SUCCESS';
export const GET_PERMISSION_GROUPS_ERROR = 'GET_PERMISSION_GROUPS_ERROR';

export const CREATE_PRIVATE_CHAT_REQUEST = 'CREATE_PRIVATE_CHAT_REQUEST';
export const CREATE_PRIVATE_CHAT_SUCCESS = 'CREATE_PRIVATE_CHAT_SUCCESS';
export const CREATE_PRIVATE_CHAT_ERROR = 'CREATE_PRIVATE_CHAT_ERROR';

export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';
