export const GET_GROUP_MEMBERS_REQUEST = 'GET_GROUP_MEMBERS_REQUEST';
export const GET_GROUP_MEMBERS_SUCCESS = 'GET_GROUP_MEMBERS_SUCCESS';
export const GET_GROUP_MEMBERS_ERROR = 'GET_GROUP_MEMBERS_ERROR';

export const GET_PERMISSION_GROUPS_REQUEST = 'GET_PERMISSION_GROUPS_REQUEST';
export const GET_PERMISSION_GROUPS_SUCCESS = 'GET_PERMISSION_GROUPS_SUCCESS';
export const GET_PERMISSION_GROUPS_ERROR = 'GET_PERMISSION_GROUPS_ERROR';
