export const GET_MY_VOUCHES_REQUEST = 'GET_MY_VOUCHES_REQUEST';
export const GET_MY_VOUCHES_SUCCESS = 'GET_MY_VOUCHES_SUCCESS';
export const GET_MY_VOUCHES_ERROR = 'GET_MY_VOUCHES_ERROR';

export const ACCEPT_VOUCH_REQUEST = 'ACCEPT_VOUCH_REQUEST';
export const ACCEPT_VOUCH_SUCCESS = 'ACCEPT_VOUCH_SUCCESS';
export const ACCEPT_VOUCH_ERROR = 'ACCEPT_VOUCH_ERROR';

export const REJECT_VOUCH_REQUEST = 'REJECT_VOUCH_REQUEST';
export const REJECT_VOUCH_SUCCESS = 'REJECT_VOUCH_SUCCESS';
export const REJECT_VOUCH_ERROR = 'REJECT_VOUCH_ERROR';
