export const baseUrl = 'https://api.otctrade.com';

const {
  REACT_APP_RECAPTCHA_PROD_KEY: RECAPTCHA_PROD_KEY,
  REACT_APP_RECAPTCHA_DEV_KEY: RECAPTCHA_DEV_KEY,
  REACT_APP_API_KEY: FIREBASE_API_KEY,
  REACT_APP_AUTH_DOMAIN: FIREBASE_AUTH_DOMAIN,
  REACT_APP_DATABASE_URL: FIREBASE_DATABASE_URL,
  REACT_APP_PROJECT_ID: FIREBASE_PROJECT_ID,
  REACT_APP_STORAGE_BUCKET: FIREBASE_STORAGE_BUCKET,
} = process.env;

export const RECAPTCHA_KEY =
  process.env.NODE_ENV === 'production'
    ? RECAPTCHA_PROD_KEY
    : RECAPTCHA_DEV_KEY;

export const PAGE_LIMIT = 4;

export const MSG_COUNT_LIMIT = 10;

export const FIRST_MESSAGE_TEXT = {
  id: 'first',
  type: 'first_message',
  text:
    'This is the very beginning of your direct message history, happy chats',
};

export const FIREBASE_CONFIG = {
  apiKey: FIREBASE_API_KEY,
  authDomain: FIREBASE_AUTH_DOMAIN,
  databaseURL: FIREBASE_DATABASE_URL,
  projectId: FIREBASE_PROJECT_ID,
  storageBucket: FIREBASE_STORAGE_BUCKET,
};

export const OFFER_STATUS_CLASS = {
  active: 'primary',
  rejected: 'warning',
  pending: 'dark',
  ended: 'light',
};

export const PROPOSAL_STATUS_CLASS = {
  active: 'primary',
  rejected: 'warning',
  pending: 'dark',
};

export const NOTIFICATION_COUNT = 5;

export const NOTIFICATION_TYPE = {
  GROUP: {
    ACTIVE: 'GROUP_ACTIVE',
    INACTIVE: 'GROUP_INACTIVE',
  },
  PERMISSION: {
    RECEIVED_APPLICATION: 'PERMISSION_RECEIVED_APPLICATION',
    REJECTED_APPLICATION: 'PERMISSION_REJECTED_APPLICATION',
    REVOKED_APPLICATION: 'PERMISSION_REVOKED_APPLICATION',
    BANNED: 'PERMISSION_BANNED',
    UNBANNED: 'PERMISSION_UNBANNED',
    GRANTED_MEMBER: 'PERMISSION_GRANTED_MEMBER',
    REVOKED_MEMBER: 'PERMISSION_REVOKED_MEMBER',
    GRANTED_ADMIN: 'PERMISSION_GRANTED_ADMIN',
    REVOKED_ADMIN: 'PERMISSION_REVOKED_ADMIN',
  },
  OFFER: {
    EXPIRED: 'OFFER_EXPIRED',
    ENDED: 'OFFER_ENDED',
    FEEDBACK: 'OFFER_FEEDBACK',
  },
  PROPOSAL: {
    RECEIVED: 'PROPOSAL_RECEIVED',
    ACCEPTED: 'PROPOSAL_ACCEPTED',
    REJECTED: 'PROPOSAL_REJECTED',
    FEEDBACK: 'PROPOSAL_FEEDBACK',
  },
  VOUCH: {
    RECEIVED: 'VOUCH_RECEIVED',
    ACCEPTED: 'VOUCH_ACCEPTED',
    REJECTED: 'VOUCH_REJECTED',
  },
  MESSAGE: {
    PRIVATE_RECEIVED: 'PRIVATE_RECEIVED',
  },
};
