export const GET_GROUP_MEMBERS_REQUEST = 'GET_GROUP_MEMBERS_REQUEST';
export const GET_GROUP_MEMBERS_SUCCESS = 'GET_GROUP_MEMBERS_SUCCESS';
export const GET_GROUP_MEMBERS_ERROR = 'GET_GROUP_MEMBERS_ERROR';
