export const GET_GROUPS_REQUEST = 'GET_GROUPS_REQUEST';
export const GET_GROUPS_SUCCESS = 'GET_GROUPS_SUCCESS';
export const GET_GROUPS_ERROR = 'GET_GROUPS_ERROR';

export const CREATE_GROUP_REQUEST = 'CREATE_GROUP_REQUEST';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_ERROR = 'CREATE_GROUP_ERROR';

export const READ_GROUP_REQUEST = 'READ_GROUP_REQUEST';
export const READ_GROUP_SUCCESS = 'READ_GROUP_SUCCESS';
export const READ_GROUP_ERROR = 'READ_GROUP_ERROR';

export const UPDATE_GROUP_REQUEST = 'UPDATE_GROUP_REQUEST';
export const UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS';
export const UPDATE_GROUP_ERROR = 'UPDATE_GROUP_ERROR';

export const DELETE_GROUP_REQUEST = 'DELETE_GROUP_REQUEST';
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS';
export const DELETE_GROUP_ERROR = 'DELETE_GROUP_ERROR';

export const APPROVE_GROUP_REQUEST = 'APPROVE_GROUP_REQUEST';
export const APPROVE_GROUP_SUCCESS = 'APPROVE_GROUP_SUCCESS';
export const APPROVE_GROUP_ERROR = 'APPROVE_GROUP_ERROR';

export const LIST_MEMBERS_REQUEST = 'LIST_MEMBERS_REQUEST';
export const LIST_MEMBERS_SUCCESS = 'LIST_MEMBERS_SUCCESS';
export const LIST_MEMBERS_ERROR = 'LIST_MEMBERS_ERROR';
